object_type: global_settings
overrides:
  "aggregates.parquet.compression.type": "gzip"
  "aggregates.create.partition.systemDefinedAggregate.threshold": 40
  "aggregates.create.withoutCompressionEstimate.enabled": true
  "aggregates.create.widening.measure.limit": 997
  "query.cache.eviction.entryAge": 50 minutes
27.02.2025 (чт) 14:21:58 EET - New update
27.02.2025 (чт) 14:24:12 EET - New update
