object_type: global_settings
overrides:
    "xmla.auth.token.enabled": true
    "otel.metrics.otlp.endpoint": http://127.0.0.1:4318
    "pgwire.auth.mode": oid_token_or_password
    "pgwire.host": 0.0.0.1