object_type: global_settings
overrides:
    "redis.parallelism.cpu_bound": 6
    "soap.marshalling.streaming.chunkTimeout": 6 minutes
    "soap.xpress.enabled": true
    "pgwire.host": 0.0.0.6
    "schema.hintedUserDefinedAggregates.nonFactTables.enabled": true
    "appDb.connectionTestQuery.enabled": true