object_type: global_settings
overrides:
  "aggregates.parquet.compression.type": "gzip"
  "aggregates.create.narrowing.enabled": true
  "query.cache.entry.sizeLimit": 5000
  "sparkSql.shufflePartitions.canary_query_role.enabled": true
  "connection.pool.maxTimeout": "12 hours"
  "connection.groups.testFilesystemTimeout": "15 secondsssss"
