object_type: global_settings
overrides:
  "aggregates.parquet.compression.type": "gzip"
  "aggregates.tableCache.password": new_password
  actor.system.name: LACHO_PIRATA_S_GOLEMIQ_H
  appDb.minIdleConnections: t