object_type: global_settings
overrides:
  "aggregates.parquet.compression.type": "gzip"
  "aggregates.create.withoutCompressionEstimate.enabled": true
  "aggregates.create.widening.measure.limit": 1062
  "query.cache.eviction.entryAge": 70 minutes

