object_type: global_settings
overrides:
    "redis.parallelism.cpu_bound": 5
    "soap.marshalling.streaming.chunkTimeout": 6 minutes
    "soap.xpress.enabled": true
    "pgwire.host": 0.0.0.6
    "we.are.invalid": 1
    "i.iam.invalid.setting": false
    "i am inproperly formatted": 5 minutes
    "atscale.setting": some value
    "schema.hintedUserDefinedAggregates.nonFactTables.enabled": true
    "appDb.connectionTestQuery.enabled": true
    "actor.system.name": system
