object_type: global_settings
overrides:
    "actor.system.name": system1
    "appDb.connectionTestQuery.enabled": true
    "schema.hintedUserDefinedAggregates.nonFactTables.enabled": false
    "pgwire.host": 0.0.0.6