object_type: global_settings
overrides:
  "aggregates.parquet.compression.type": "gzip"
  "aggregates.create.partition.systemDefinedAggregate.threshold": 4000
  "aggregates.create.withoutCompressionEstimate.enabled": true
  "aggregates.create.widening.measure.limit": 1061
  "query.cache.eviction.entryAge": 60 minutes
  "aggregates.configuration.maximum_concurrent_materializations": 6

