object_type: global_settings
overrides:
  "aggregates.parquet.compression.type": "gzip"
  "aggregates.create.partition.systemDefinedAggregate.threshold": 40
  "aggregates.create.withoutCompressionEstimate.enabled": true
  "aggregates.create.widening.measure.limit": 997
  "query.cache.eviction.entryAge": 50 minutes

  New update: 27.02.2025 (чт) 14:51:21 EET
  New update: 27.02.2025 (чт) 14:51:22 EET
  New update: 27.02.2025 (чт) 15:04:08 EET
  New update: 27.02.2025 (чт) 15:04:09 EET
  New update: 27.02.2025 (чт) 15:19:48 EET
