object_type: global_settings
overrides:
  "aggregates.parquet.compression.type": "gzip"
  "aggregates.create.partition.systemDefinedAggregate.threshold": 40
  "aggregates.create.withoutCompressionEstimate.enabled": true
  "aggregates.create.widening.measure.limit": 997
  "query.cache.eviction.entryAge": 50 minutes

  New update: 27.02.2025 (чт) 14:51:21 EET
  New update: 27.02.2025 (чт) 14:51:22 EET
  New update: 27.02.2025 (чт) 15:04:08 EET
  New update: 27.02.2025 (чт) 15:04:09 EET
  New update: 27.02.2025 (чт) 15:19:48 EET
  New update: 27.02.2025 (чт) 15:19:49 EET
  New update: 27.02.2025 (чт) 15:19:50 EET
  New update: 27.02.2025 (чт) 15:20:18 EET
  New update: 27.02.2025 (чт) 15:20:19 EET
  New update: 27.02.2025 (чт) 15:20:20 EET
  New update: 27.02.2025 (чт) 15:21:16 EET
  New update: 27.02.2025 (чт) 15:21:18 EET
  New update: 27.02.2025 (чт) 15:21:19 EET
  New update: 27.02.2025 (чт) 15:22:15 EET
  New update: 27.02.2025 (чт) 15:22:16 EET
  New update: 27.02.2025 (чт) 15:22:17 EET
  New update: 27.02.2025 (чт) 15:54:11 EET
  New update: 27.02.2025 (чт) 15:54:12 EET
  New update: 27.02.2025 (чт) 15:54:15 EET
